import './globals.css';
import Providers from '@/components/providers';

export const metadata = {
    title: 'Monitoring',
    description: 'Generated by Vahid Heydari',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" suppressHydrationWarning={true}>
            <body>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
